import ThemeRegistry from "../components/ThemeRegistry";
import Footer from "../components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <ThemeRegistry>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              minHeight: "100vh",
            }}
          >
            {/* Main content */}
            <main style={{ flex: 1 }}>{children}</main>
            
            {/* Footer */}
            <Footer />
          </div>
        </ThemeRegistry>
      </body>
    </html>
  );
}
