import ThemeRegistry from "../components/ThemeRegistry";
import Footer from "../components/Footer";
import { AuthProvider } from "../contexts/AuthContext";
import HeaderWrapper from "../components/HeaderWrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body style={{ margin: 0 }}>
          <ThemeRegistry>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                minHeight: "100vh",
              }}
            >
              <HeaderWrapper />
              <main style={{ flex: 1 }}>{children}</main>
              <Footer />
            </div>
          </ThemeRegistry>
        </body>
      </html>
    </AuthProvider>
  );
}
